### ISSUE TITLE
command 'vscode.previewHtml' not found

### ISSUE THREAD

**Issue by sapan-sha** [red-gate/foundry#24] opened 2019-05-06 18:33 UTC
Ctrl + Shift + P
SQL Search : Search in Active Connection 
"someSearchText"
It throw an popup "command 'vscode.previewHtml' not found"

**Comment by stanislavHamara** [comment] 2019-05-07 07:31
Duplicate of https://github.com/red-gate/foundry/issues/23

**Closed by stanislavHamara** 2019-05-07 07:31 UTC
Labels: bug, sql search

**Comment by SamSharaf** [comment] 2019-05-10 19:40
@stanislavHamara  Kindly reopen the original issue:
https://github.com/red-gate/foundry/issues/23#issuecomment-491386190
