### ISSUE TITLE
SQL Search Result - dark theme problem (Azure Data Studio Extension) 

### ISSUE THREAD

**Issue by ian902792** [red-gate/foundry#34] opened 2019-11-07 06:54 UTC
![2019-11-07_144550](https://user-images.githubusercontent.com/51110317/68366510-76d62f00-016e-11ea-9a4f-6098f092177a.jpg)

**Comment by cjheppell** [comment] 2019-11-19 09:47
Closing this issue, as it's a duplicate of https://github.com/red-gate/foundry/issues/26

**Closed by cjheppell** 2019-11-19 09:47 UTC
Labels: bug, duplicate, sql search
