### ISSUE TITLE
Search not works. Azure Data Studio v1.15.0

### ISSUE THREAD

**Issue by alxlib** [red-gate/foundry#39] opened 2020-02-19 11:27 UTC
Redgate SQL Search v 0.4.0

Message : command 'sqlSearch.reindexActiveConnection' not found
                 command 'sqlSearch.searchInActiveConnection' not found

**Comment by adrianbanks** [comment] 2020-02-19 13:30
Duplicate of #38.

We have fixed this issue and released SQL Search v0.4.0 to address the problem. The latest version can be downloaded from here and will appear in the extension market place soon.

**Closed by adrianbanks** 2020-02-19 13:30 UTC
